
package com.zhiwei.webservice.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherForJDKServiceImplService", targetNamespace = "http://service.webservice.zhiwei.com/", wsdlLocation = "http://localhost:8080/weatherService?wsdl")
public class WeatherForJDKServiceImplService
    extends Service
{

    private final static URL WEATHERFORJDKSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEATHERFORJDKSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WEATHERFORJDKSERVICEIMPLSERVICE_QNAME = new QName("http://service.webservice.zhiwei.com/", "WeatherForJDKServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/weatherService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERFORJDKSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WEATHERFORJDKSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WeatherForJDKServiceImplService() {
        super(__getWsdlLocation(), WEATHERFORJDKSERVICEIMPLSERVICE_QNAME);
    }

    public WeatherForJDKServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERFORJDKSERVICEIMPLSERVICE_QNAME, features);
    }

    public WeatherForJDKServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WEATHERFORJDKSERVICEIMPLSERVICE_QNAME);
    }

    public WeatherForJDKServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERFORJDKSERVICEIMPLSERVICE_QNAME, features);
    }

    public WeatherForJDKServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherForJDKServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherForJDKServiceImpl
     */
    @WebEndpoint(name = "WeatherForJDKServiceImplPort")
    public WeatherForJDKServiceImpl getWeatherForJDKServiceImplPort() {
        return super.getPort(new QName("http://service.webservice.zhiwei.com/", "WeatherForJDKServiceImplPort"), WeatherForJDKServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherForJDKServiceImpl
     */
    @WebEndpoint(name = "WeatherForJDKServiceImplPort")
    public WeatherForJDKServiceImpl getWeatherForJDKServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.zhiwei.com/", "WeatherForJDKServiceImplPort"), WeatherForJDKServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERFORJDKSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WEATHERFORJDKSERVICEIMPLSERVICE_EXCEPTION;
        }
        return WEATHERFORJDKSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
