
package com.zhiwei.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherForJDKServiceImpl", targetNamespace = "http://service.webservice.zhiwei.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherForJDKServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://service.webservice.zhiwei.com/", className = "com.zhiwei.webservice.service.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://service.webservice.zhiwei.com/", className = "com.zhiwei.webservice.service.QueryResponse")
    @Action(input = "http://service.webservice.zhiwei.com/WeatherForJDKServiceImpl/queryRequest", output = "http://service.webservice.zhiwei.com/WeatherForJDKServiceImpl/queryResponse")
    public String query(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
